#!/bin/bash
# $Id: rogueMTAs,v 1.2 2020/10/16 15:07:21 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/rogueMTAs,v $
# $Revision: 1.2 $
# Author C W Fulford.
# Copyright 2019 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: rogueMTAs,v 1.2 2020/10/16 15:07:21 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
hostid=tx-slkmail
max=2000
while [ $# -gt 0 ] ;do
	case $1 in 
		-d) set -x;debug=0;shift;;
		-h) hostid=$2;shift 2;;			
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.2 $ $Date: 2020/10/16 15:07:21 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done

tmp=/tmp/$1.$$
sorted=/tmp/$1.sorted.$$
ssh $hostid cat /var/log/maillog|
 grep "did not issue" |sed -ne 's/^[^\[]*\[[0-9]*\][^\[]*\[\([0-9\.]*\)\].*/\1/p'>$tmp
cat $tmp|grep -v "10.0.0.32"|sort -u |
while read ip ;do
	c=`grep $ip  $tmp|wc -l`
	printf "%-15s %5i\n" $ip $c
done |sort -nk 2 

	
rm $tmp
